# Generated by Django 2.0.1 on 2018-01-23 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0003_auto_20180122_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbook.Chapter'),
        ),
    ]
