# Generated by Django 2.0.1 on 2018-01-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0004_auto_20180122_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.IntegerField(),
        ),
    ]
